project:
  output-dir: ./docs/en
  render:
    - "index.qmd"
    - "features.qmd"
    - "./source/en/*.qmd"

website:
  title: "Atlas of variation in spoken varieties of Russian"
  navbar:
    left:
      - href: index.qmd
        text: home
      - href: features.qmd
        text: features
    right:
      - text: "ru"
        href: ./../index.html

lang: en
