project:
  type: website

profile:
  default: russian
  group: [russian, english]
  
execute: 
  echo: false
  message: false
  warning: false
        
format:
  html:
    theme: cosmo
    embed-resources: true
    page-layout: full
