---
link-citations: true
output:
  html_document:
    number_sections: false
    anchor_sections: true
    pandoc_args: --shift-heading-level-by=-1
---

::: {.content-visible when-profile="russian"} 
## Атлас вариативности устной речи в регионах России

Вариативность в нашем проекте понимается как наличие нескольких способов выражения одного морфосинтаксического признака. Интерес к исследованию языковой вариативности впервые появился в работах американских лингвистов, предложивших это понятие [Labov 1963; Wolfram 1969; Trudgill 1974]. Вариативность возможна между регионами, социальными группами и отдельными носителями [Auer, Schmidt 2010; Meyerhoff 2011].

Важно, что при этом варианты рассматриваются как равноправные. Такой подход предполагает, что вариативность – это норма, а фиксация разнообразия помогает лучше понять устройство языка [Гренобль 2021]. Также важно, что в нашем проекте материалом служит спонтанная речь.

Большое количество региональных разновидностей русского языка описано в диалектологии, при этом обычно принимаются во внимание только отличия диалектной речи от литературной. В последнее время в российской диалектологии  развивается вариационистский подход, предполагающий сравнение стандартных и нестандартных черт и поиск объяснений наблюдаемой вариативности [Daniel et al., 2019; Малышева, Ронько 2020; Ter-Avanesova, Daniel 2023].

Нестандартные морфосинтаксические особенности активно изучаются на материале контактных разновидностей русского языка. Описывается речь определённых билингвальных сообществ в целом, а также отдельные вариативные особенности с учётом разных факторов [Daniel et al. 2010; Mustajoki et al. 2010; Резанова, Дыбо 2019; Stoynova 2019; Винклер и др. 2021; Наккарато и др. 2020; Dobrushina, Kultepina 2021].

Наш проект основан на данных билингвальных и диалектных устных корпусов международной лаборатории языковой конвергенции НИУ ВШЭ. Сейчас в них представлены аудиозаписи и расшифровки речи из 22 регионов, данные пополняются.  Дополнительную информацию об источниках материала можно получить на странице конкретного корпуса.

Билингвы --- носители одного или нескольких языков России, для которых русский является неродным, или вторым (Я2, L2); материалы билингвальной речи собраны в Дагестане, Карелии, Башкортостане, Удмуртии, Чувашии, Марий Эл, Ханты-Мансийском автономном округе, а также цыганском поселении на территории г. Перми. Диалектные материалы записаны от сельских жителей следующих областей: Архангельской, Новгородской, Псковской, Тверской, Костромской, Ивановской, Смоленской, Калужской, Рязанской, Брянской, Липецкой, Белгородской, Ростовской, а также г. Звенигород и окружающих его деревень Московской области. 

### Как ссылаться на ресурс

Г. Мороз, М. Алимова, А. Гришанова, Н. Кошелюк, А. Яковлева, С. Земичева, К. Наккарато. (2025). Атлас вариативности устной речи в регионах России. Москва: Linguistic Convergence Laboratory, HSE University.


### Финансовая поддержка

Исследование выполнено за счет гранта Российского научного фонда № 24-28-01097, <https://rscf.ru/project/24-28-01097/> 

:::

::: {.content-visible when-profile="english"} 
## Atlas of variation in spoken varieties of Russian

Variability in our project is understood as the presence of multiple ways of expressing a single morphosyntactic feature. Interest in the study of linguistic variability first appeared in the works of American linguists who proposed this concept [Labov 1963; Wolfram 1969; Trudgill 1974]. Variability is possible between regions, social groups, and individual speakers [Auer, Schmidt 2010; Meyerhoff 2011].

It is important that these variations are considered as equally valid among speakers. This approach assumes that variability is the norm, and documenting diversity helps to better understand the structure of language [Grenoble 2021]. It is also important that our project utilizes spontaneous speech.

A large amount of regional diversity in the Russian language is described in dialectology, with attention typically paid only to the differences between dialectal speech and standard language. Recently, variationalist approaches have been developing in Russian dialectology, which involve comparing standard and non-standard features and seeking explanations for the observed variability [Daniel et al., 2019; Malysheva, Ronko 2020; Ter-Avanesova, Daniel 2023].

Non-standard morphosyntactic features are actively studied using material from contact language varieties of Russian. The speech  of specific bilingual communities as a whole, as well as individual variational features taking into account various factors, are  described [Daniel et al. 2010; Mustajoki et al. 2010; Rezanova, Dybo 2019; Stoynova 2019; Winkler et al. 2021; Nakkarato et al.  2020; Dobrushin, Kultepina 2021].

Our project is based on data from bilingual and dialectal spoken corpora of the Linguistic Convergence Laboratory at HSE University. Currently, audio recordings and transcriptions of speech from 22 regions are presented, and the data is being supplemented. Additional information about the sources of the material can be found on the page of the specific corpus.

Bilinguals are native speakers of one or more languages of Russia for whom Russian is not native or a second language (L2); bilingual speech materials have been collected in Dagestan, Karelia, Bashkortostan, Udmurtia, Chuvashia, Mari El, Khanty-Mansia, as well as in a Gypsy settlement in the city of Perm. Dialectal materials were recorded from rural residents of the following regions: Arkhangelsk, Novgorod, Pskov, Tver, Kostroma, Ivanovo, Smolensk, Kaluga, Ryazan, Bryansk, Lipetsk, Belgorod, Rostov, as well as the city of Zvenigorod and the surrounding villages of the Moscow region.

### How to cite

G. Moroz, M. Alimova, A. Grishanova, N. Koshelyuk, A. Yakovleva, S. Zemicheva, C. Naccarato. (2025). Atlas of variation patterns in spoken corpora of Russian. Moscow: Linguistic Convergence Laboratory, HSE University.
  
### Financial support

The study conducted in Linguistic Convergence Laboratory and was funded by the Russian Science Foundation, project No. 24-28-01097, <https://rscf.ru/en/project/24-28-01097/>
:::