---
title: Пропуск предлога из
author: Анна Гришанова
date: 'Last update: `r lubridate::make_datetime(year = 2024, month = 12, day = 1)`'
output:
  html_document:
    number_sections: true
    anchor_sections: true
    pandoc_args: --shift-heading-level-by=-1
---

```{r, include=FALSE}
library(tidyverse)
readxl::read_xlsx('../../data/data.xlsx') |> 
  filter(feature_id == 7) ->
  db
```

Здесь будет описание

##

::: {.panel-tabset}

### Вариативные носители

```{r}
library(waffle)
db |> 
  mutate(standardness = if_else(non_standard == 0, 'невариативные носители', 'вариативные носители')) |> 
  count(corpus_ru, standardness) |> 
  ggplot(aes(fill = standardness, values = n))+
  geom_waffle(colour = 'white', size = 0.5)+
  facet_wrap(~corpus_ru, ncol = 2) +
  scale_fill_manual(name = NULL, values = c('#c68958', '#9AC0CD')) +
  theme_enhance_waffle()+
  theme_void()+
  theme(legend.position = 'top', text = element_text(size = 15))
```

### Карта

```{r}
db |> 
  mutate(standardness = if_else(non_standard == 0, 'невариативные носители', 'вариативные носители')) |> 
  count(corpus_ru, standardness, latitude, longitude, url) |> 
  mutate(url = str_glue('<a href={url}>{corpus_ru}</a>')) |> 
  pivot_wider(names_from = standardness, values_from = n) ->
  for_map
  
if(!('невариативные носители' %in% colnames(for_map))) {
  for_map |> 
    mutate(`невариативные носители` = 0) ->
    for_map
}

library(leaflet)
library(leaflet.minicharts)

leaflet() |> 
  addTiles() |> 
  addMinicharts(lng = for_map$longitude, 
                lat = for_map$latitude,
                type = 'pie',
                chartdata = for_map[, c('невариативные носители', 'вариативные носители')],
                showLabels = TRUE,
                popup = leaflet.minicharts::popupArgs(html = for_map$url))
```

### Вариативность

```{r}
library(tidytext)
db |> 
  filter(non_standard > 0) |> 
  mutate(total = non_standard + standard,
         ratio = non_standard/total,
         speaker = reorder_within(speaker, by = ratio, within = corpus)) |> 
  ggplot(aes(ratio, speaker))+
  geom_point()+
  facet_wrap(~corpus_ru, scales = 'free_y', ncol = 2)+
  scale_y_reordered()+
  scale_x_continuous(labels = scales::percent)+
  labs(x = NULL, y = NULL)+
  theme_minimal()+
  theme(axis.text.y = element_blank(), text = element_text(size = 15))
```

### Данные

```{r}
db |> 
  select(corpus_ru, speaker, non_standard, standard) |> 
  DT::datatable(class = 'cell-border stripe', 
    rownames = FALSE, 
    filter = 'top', 
    extensions = 'Buttons',
    options = list(pageLength = 42, 
                   autoWidth = TRUE, 
                   info = FALSE,
                   dom = 'fBltp',
                   buttons = list(list(extend = 'collection',
                                       buttons = c('csv', 'excel', 'pdf'),
                                       text = '<i class="fas fa-download"></i>')),
                   paginate = TRUE))
```
:::


